# Generated by Django 4.1.4 on 2023-02-20 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0015_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=30)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=0)),
                ('minimum_amount', models.IntegerField(default=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase.userdetail')),
            ],
        ),
    ]
