# Generated by Django 4.1.4 on 2023-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0016_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='uimage',
            field=models.ImageField(blank=True, null=True, upload_to='imagestore/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordertype',
            field=models.CharField(choices=[('Cash on delivery', 'Cash on delivery'), ('Paypal', 'Paypal'), ('Razorpay', 'Razorpay')], default='Cash on delivery', max_length=50),
        ),
    ]
