# Generated by Django 4.1.4 on 2023-02-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase', '0017_userdetail_uimage_alter_order_ordertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='uotp',
            field=models.IntegerField(null=True),
        ),
    ]
